# -*- coding: utf-8 -*-
"""dbscan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbWJbholC5Pv073SAwsTKrjjlvhJCFnz
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score

url = "https://raw.githubusercontent.com/RafiFadhal/dbscan/main/dataset_dbscan_moons.csv"
df = pd.read_csv(url)

X = df[['Fitur_1', 'Fitur_2']].values

model = DBSCAN(eps=0.2, min_samples=5)
model.fit(X)
labels = model.labels_

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_outlier = list(labels).count(-1)
sil_score = silhouette_score(X, labels)

print(f'Jumlah klaster: {n_clusters}')
print(f'Jumlah outlier: {n_outlier}')
print(f'Silhouette Score: {sil_score:.2f}')

plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='plasma', s=50)
plt.title(f'Hasil Clustering DBSCAN\nKlaster: {n_clusters} | Outlier: {n_outlier} | Silhouette Score: {sil_score:.2f}')
plt.xlabel('Fitur 1')
plt.ylabel('Fitur 2')
plt.grid(True)
plt.show()